#  120CS1109 Akash Poudel

 <h1>Neural Network Implementation for XOR from scratch </h1>

In [1]:
#Initializing x and y with numpy
import numpy as np
X=np.array(([0,0],[0,1],[1,0],[1,1]), dtype=float)
y=np.array(([0],[1],[1],[0]), dtype=float) #expected output

<h3>Activation Function </h1>

In [6]:
# sigmoid  function
def sigmoid(t):
    '''This will return the sigmoid value of the function'''
    return 1/(1+np.exp(-t))


In [7]:
# derivative sigmoid
def sigmoid_derivative(d):
    return d * (1 - d)


In [8]:
# Class definition
class NeuralNetwork:
    def __init__(self, x,y):
        self.input = x #initializing x
        self.weights1= np.random.rand(self.input.shape[1],4) #initializing random weights
        self.weights2 = np.random.rand(4,1)#considering we have 4 nodes in the hidden layer
        self.y = y#initializing y
        self.bias1 = np.random.uniform(0, 1)
        self.bias2 = np.random.uniform(0, 1)
        self.output = np. zeros(y.shape)#initializing the output


    def feedforward(self):
        '''This will perform the forward propagation for the next 2 layers'''
        self.layer1 = sigmoid(np.dot(self.input, self.weights1)+self.bias1)#calcuation of w_T*X+b for layer1
        self.layer2 = sigmoid(np.dot(self.layer1, self.weights2)+self.bias2)#calcuation of w_T*X+b for layer2
        return self.layer2

    def backprop(self):
        delta_output = (self.y - self.output) * sigmoid_derivative(self.output)
        delta_hidden = delta_output.dot(self.weights2.T) * sigmoid_derivative(self.layer1)

        derv_weights2 = self.layer1.T.dot(delta_output)
        derv_weights1 = self.input.T.dot(delta_hidden)

        self.weights1 += derv_weights1 #update weights for hidden layer
        self.weights2 += derv_weights2 # update weights for output layer
        self.bias1 += np.sum(delta_hidden, axis=0) #update bias for hidden layer
        self.bias2 += np.sum(delta_output, axis=0) #update bias for output layer

    def train(self, X, y):
        self.output = self.feedforward()#Forward Propagation
        self.backprop()#Backward Propagation

In [9]:
model=NeuralNetwork(X,y)
for i in range(2500):
    if i % 100 ==0:#For each 100 epochs output will come
        print ("for iteration # " + str(i) + "\n")
        print ("Input : \n" + str(X))
        print ("Actual Output: \n" + str(y))
        print ("Predicted Output: \n" + str(model.feedforward()))
        print ("Loss: \n" + str(np.mean(np.square(y - model.feedforward())))) # mean sum squared loss
        print ("\n")

    model.train(X, y)

for iteration # 0

Input : 
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
Actual Output: 
[[0.]
 [1.]
 [1.]
 [0.]]
Predicted Output: 
[[0.88338441]
 [0.90240281]
 [0.90484248]
 [0.91955476]]
Loss: 
0.41113228675233787


for iteration # 100

Input : 
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
Actual Output: 
[[0.]
 [1.]
 [1.]
 [0.]]
Predicted Output: 
[[0.49290239]
 [0.50616949]
 [0.49679872]
 [0.50930423]]
Loss: 
0.249855916461297


for iteration # 200

Input : 
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
Actual Output: 
[[0.]
 [1.]
 [1.]
 [0.]]
Predicted Output: 
[[0.48076025]
 [0.51169183]
 [0.49599298]
 [0.52003445]]
Loss: 
0.24850854851505277


for iteration # 300

Input : 
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
Actual Output: 
[[0.]
 [1.]
 [1.]
 [0.]]
Predicted Output: 
[[0.45016073]
 [0.53440821]
 [0.49626288]
 [0.54097187]]
Loss: 
0.24145551370499208


for iteration # 400

Input : 
[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
Actual Output: 
[[0.]
 [1.]
 [1.]
 [0.]]
Predicted Output: 
[[0.31663969]
 [0.6281202